services:
  web:
    depends_on:
      - postgres_db
    build:
      context: ./web
      dockerfile: Dockerfile
    image: django-k8ss:v1
    environment:
      - PORT=8021
    env_file:
      - web/.env
    ports:
      - "8001:8021"
    command: sh -c 'chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh'
    volumes:
      - staticfiles:/app/staticfiles/

  
  postgres_db:
    image: postgres
    restart: always
    command: -p 5432
    env_file:
      - web/.env
    expose:
      - 5432
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    
  redis_db:
    image: redis
    restart: always
    expose:
      - '6381'
    ports:
      - '6381:6381'
    volumes:
      - redis_data:/data
    entrypoint: redis-server --appendonly yes --port 6381

volumes:
  postgres_data:
  redis_data:
  staticfiles: