apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-k8s-web-deployment
spec:
  selector:
    matchLabels:
      app: django-k8s-web-deployment
  template:
    metadata:
      labels:
        app: django-k8s-web-deployment
    spec:
      containers:
      - name: django-k8s-web
        image: registry.digitalocean.com/cfe-k8ss/django-k8s-web:latest
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: devapp-web-prod-env
        env:
          - name: PORT
            value: '8002'
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8002
      imagePullSecrets:
        - name: cfe-k8ss 


---

apiVersion: v1
kind: Service
metadata:
  name: django-k8s-web-service
spec:
  type: LoadBalancer
  selector:
    app: django-k8s-web-deployment
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8002
